### ISSUE TITLE
Rule proposal: warn when import uses ../ too many times

### ISSUE THREAD

**Issue by lencioni** [benmosher/eslint-plugin-import#776] opened 2017-03-23 15:37 UTC
I'm not sure if there is a term for this, and describing it is a bit awkward, but I'll give it a shot.

Let's say you have a directory structure like:

```
/foo/bar/baz.js
/foo/bar/boop.js
```

In baz.js you want to import boop.js. Normally you would write it like this:

```js
import boop from './boop';
```

However, if you aren't paying attention, especially when moving code around, you might end up doing something like this instead:

```js
import boop from '../bar/boop';
```

Or in a more deeply nested structure, you might end up with something like this that overshoots its target:

```js
import boop from '../../../bar/boop';
```

It would be really great to have a rule that warns against these.

**Comment by ljharb** [comment] 2017-03-23 17:12
Perhaps if a relative import path does not match `path.normalize()` of that path, it warns?

**Comment by danny-andrews** [comment] 2017-08-16 20:21
@ljharb Dupe of https://github.com/benmosher/eslint-plugin-import/issues/471?

**Comment by ljharb** [comment] 2017-08-16 20:59
Indeed, this is a duplicate of #471.

**Closed by ljharb** 2017-08-16 20:59 UTC
Labels: evaluating, rule proposal
