### ISSUE TITLE
Fails on "Error: Cannot find module 'es6-set'"

### ISSUE THREAD

**Issue by Retsam** [benmosher/eslint-plugin-import#611] opened 2016-10-05 17:38 UTC
I'm seeing an issue trying to use this plugin: it fails on "cannot find module 'es6-set'".  It appears that [9880ae7](https://github.com/benmosher/eslint-plugin-import/commit/9880ae7db99865a6e4c887151d59dd4de97debfa) removed `es6-set` from the package.json, but there's still a reference to `es6-set` in [max-dependencies.js](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/max-dependencies.js)

**Comment by benmosher** [comment] 2016-10-06 09:59
duplicate of #604, thanks!

**Closed by benmosher** 2016-10-06 09:59 UTC
