### ISSUE TITLE
why eslint-plugin-import plugin dosen't support webpack extensions like .vue and alias?

### ISSUE THREAD

**Issue by zp1112** [benmosher/eslint-plugin-import#723] opened 2017-01-18 02:05 UTC
**Tell us about your environment**

* **ESLint Version:**3.13.1
* **Node Version:**v6.9.0
* **npm Version:**3.10.8
* **webpack Version:**1.14.0
* **vue Version:**2.1.9

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: [path.resolve(__dirname, '../app/index.js')],
  output: {
    path: path.resolve(__dirname, '../output/static'),
    publicPath: 'static/',
    filename: '[name].[hash].js',
    chunkFilename: '[id].[chunkhash].js'
  },
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.vue'],
    alias: {
      vue: 'vue/dist/vue.js',
      components: path.resolve(__dirname, '../app/components')
    }
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: '../index.html',
      template: path.resolve(__dirname, '../app/index.html'),
      inject: true
    })
  ]
};




```

**What did you do? Please include the actual source code causing the issue.**

```js
// using extensions['.vue'] error png1
import Vue from 'vue';
import App from './components/app';

// using alias error png2
import Vue from 'vue';

//this import succeed ,but throw an eslint error
import App from 'components/app.vue';

```

png1
![image](https://cloud.githubusercontent.com/assets/14245159/22013948/769cd3d2-dcd6-11e6-88af-8eeef9ddd805.png)

png2
![image](https://cloud.githubusercontent.com/assets/14245159/22013987/9351b326-dcd6-11e6-8d59-4a993670baab.png)

**What did you expect to happen?**

no eslint error

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by zp1112** [comment] 2017-01-18 02:49
I fixed it.It's atom's  problem ，the plugin named js-hiperclick，default extensions are setted to jump to .js .node .coffee ,add .vue and it works.

![image](https://cloud.githubusercontent.com/assets/14245159/22049022/bacfb944-dd6b-11e6-82e0-63a86dd2f6c7.png)

**Comment by zp1112** [comment] 2017-01-18 02:54
It fied atom's jump problem,and also needs to setting .eslintrc.json config like this

```js
"settings": {
    "import/resolver": {
      "webpack": {
        "config": "build/webpack.config.js"
      }
    }
  },
"rules": {
    "import/extensions": ["error", "always", {
      "js": "never",
      "vue": "never"
    }],
...
}
```

**Comment by zp1112** [comment] 2017-01-18 02:57
but the alias setting desn't work still

**Comment by tokyoincode** [comment] 2017-01-20 04:55
Looks like it's `linter-eslint` that's causing this.

[See here](https://github.com/benmosher/eslint-plugin-import/issues/723)

Adding an empty `.eslintignore` file in the project root folder and restarting Atom seems to work for some people. Didn't work for me. 

In my case, running eslint via gulp works, Atom does not like it though.

**Comment by zp1112** [comment] 2017-01-20 05:46
@tokyoincode Didn't work for me either.In my case, running eslint via webpack, Atom seems does not like it though either.How ?I hope some one can fix it one day.

**Comment by juhaelee** [comment] 2017-01-22 00:14
@zp1112 is it not working for you when you run `eslint` on the command line? or is it just in Atom?

**Comment by zp1112** [comment] 2017-01-22 00:36
@juhaelee I do not know how to distinguish between these two aspects,i think eslint run in atom automatically when i edit,is that right?and i didn't run in other editors.so i think it's eslint problem,because other people have the same problem without using atom.

**Comment by joshlangner** [comment] 2017-07-27 20:33
Anyone solve this?

**Comment by silvenon** [comment] 2018-04-14 10:37
I couldn't reproduce the issue. Maybe it got fixed in the meantime? Could you provide a minimal demo if this is still an issue for you?

**Comment by ForsakenHarmony** [comment] 2018-07-31 20:26
I'm still getting this

![](https://i.imgur.com/oVaIjHS.png)

**Comment by ozguruysal** [comment] 2018-08-11 17:01
Try installing [eslint-import-resolver-webpack](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack) if you haven't already.

**Closed** 2020-02-18 01:56 UTC
Labels: question
