### ISSUE TITLE
`import/default` does not support `export { default } from` pattern

### ISSUE THREAD

**Issue by proteriax** [benmosher/eslint-plugin-import#2010] opened 2021-03-21 05:45 UTC
`import/default` will complain about `No default export found in imported module "x"` when `x` uses

```js
export { default } from 'another-module';
```

**Comment by ljharb** [comment] 2021-03-21 05:48
This is basically a duplicate of #1938. See #1939.

**Closed** 2021-03-21 05:57 UTC
