### ISSUE TITLE
An alphabetical order rule?

### ISSUE THREAD

**Issue by fa93hws** [benmosher/eslint-plugin-import#1406] opened 2019-07-06 02:22 UTC
Hi!
I found that the alphabetical order import rule is very useful.
Do you mind I add a new rule for that?
Or an option to existed order rule?

**Comment by ljharb** [comment] 2019-07-06 04:46
Why is it useful? What rule are you referring to?

Either way it’d be an option to the existing rule, not a new one.

**Comment by fa93hws** [comment] 2019-07-06 05:35
Hi, we are a typescript team and are migrating to eslint from the tslint.
While the import order rule is quite different between that in eslint and the tslint.
I think it might be useful for other team who migrated from tslint as well.

Thanks, I will make such a rule when I have time.

**Comment by ljharb** [comment] 2019-07-06 05:38
Closing as a duplicate of #1311.

**Comment by gustavopch** [comment] 2019-10-05 14:26
> Closing as a duplicate of #1311.

How is this is a duplicate of #1311? Alphabetical order is only mentioned there, but it's not the point of the issue.

**Comment by sveyret** [comment] 2019-11-12 14:27
I also like very much the alphabetical order of the `tslint` rule, because when there are lot of imports in a file, it is far easier to find if one needs to be added or not. Probably should it be an option of the already existing `order` rule. What would be great also, to conform to `tslint` rule, would be to be able to sort imported members from a library by alphabetical order, and to have the ability to put lowercase starting members at the end. See https://palantir.github.io/tslint/rules/ordered-imports/

Would you accept PR for that?

**Comment by caribou-code** [comment] 2019-11-25 15:23
This would be a useful addition to the package. For example in a React project we can already sort props, propTypes, defaultProps and more alphabetically with rules such as `react/jsx-sort-default-props`, `react/jsx-sort-props` and `react/sort-prop-types`.

For unordered lists of code such as imports, exports and objects, it makes sense to group and sort these so there's some consistent order throughout a project. `import/order` already handles the grouping, but being able to sort alphabetically within those groups would be beneficial.

**Comment by ljharb** [comment] 2019-11-26 00:27
One challenge is that bindingless imports (`import 'path'` versus `import x from 'path'`) are by convention side-effecting, so nothing should be reordered across them, and they should not be reordered themselves.

However, yes, after some thought I think it does make sense to add this as an option to the `order` rule. A PR would be appreciated.

**Closed** 2019-12-07 01:44 UTC
Labels: enhancement, help wanted, import/export ordering
