### ISSUE TITLE
Parse errors in imported module

### ISSUE THREAD

**Issue by AsaAyers** [benmosher/eslint-plugin-import#143] opened 2015-12-08 15:12 UTC
I'm using Webpack + Babel5 with eslint + babel-eslint. Every jsx file I import seems to produce these two errors:

    13:21  error    Parse errors in imported module './section.jsx'                 import/default
    13:21  warning  Parse errors in imported module './section.jsx'                 import/no-named-as-default

I also tried https://www.npmjs.com/package/eslint-import-resolver-webpack but it doesn't seem to make any difference.

From [Import Parser](https://github.com/benmosher/eslint-plugin-import#importparser). "If you're using babel-eslint as ESLint's parser, you probably don't need to specify it here (anymore, as of v0.9)." Why "probably"? Do I need to specify this, and how would I if I'm using Babel?

**Comment by benmosher** [comment] 2015-12-08 15:27
I switched to Babylon as the default `import/parser`. Thought it would help more than it has.

I've got #141 open to figure out how to solve this long term. In the mean time, using `import/parser: babel-eslint` should solve it for you.

**Comment by AsaAyers** [comment] 2015-12-08 15:32
Thanks. That worked.

I also just figured out that in some cases the problem is object rest spread, which is optional in Babel. I don't know anything about Babylon.

I still think the documentation should be updated before closing this issue though.

**Comment by benmosher** [comment] 2015-12-08 15:56
Yeah, the thing I was trying to avoid is standing up a full-on Babel parser just to parse dependencies for exports... the problem is, Babylon doesn't care what's in the `.babelrc`, but `babel-eslint` does.

Also wanted to avoid the constant confusion around configuring the parser for ESLint twice.

I think the right long-term answer is probably just executing on https://github.com/eslint/eslint/issues/3670.

> I still think the documentation should be updated before closing this issue though.

I agree, will update the language (or accept a PR of updated language? 😁) before closing this.

**Closed** 2015-12-14 12:09 UTC
