### ISSUE TITLE
autofix do not work well with named import and default import

### ISSUE THREAD

**Issue by agrcrobles** [benmosher/eslint-plugin-import#1432] opened 2019-08-02 09:23 UTC
So I have

```jsx
import Utils from '../../lib/utils'
import { selectActiveCurrencyPrice } from '../../lib/utils'
```

And if then it runs `eslint --fix` I get:

```jsx
import { selectActiveCurrencyPrice } from Utils from '../../lib/utils'
```

Thanks!

**Comment by ljharb** [comment] 2019-08-03 01:57
What version of eslint-plugin-import do you have?

See also, #1431 and #1403 - this seems like a duplicate of #1403?

**Closed** 2020-02-27 21:47 UTC
