### ISSUE TITLE
Add sorting in `order`.

### ISSUE THREAD

**Issue by rodoabad** [benmosher/eslint-plugin-import#952] opened 2017-10-18 19:32 UTC
I' like `order` to have the same the member sort rule that `sort-imports` have.

```
import {hashHistory} from 'react-router';
import {syncHistoryWithStore} from 'react-router-redux';
```

VS

```
import {syncHistoryWithStore} from 'react-router-redux';
import {hashHistory} from 'react-router'; // error
```

**Comment by jshado1** [comment] 2018-03-28 14:37
Duplicate of #389; fix pending #629

**Comment by ljharb** [comment] 2018-03-28 20:42
Closing as a duplicate of #389.

**Closed by ljharb** 2018-03-28 20:42 UTC
Labels: import/export ordering
