### ISSUE TITLE
Bug: import/no-extraneous-dependencies doesn't work with empty dependencies

### ISSUE THREAD

**Issue by mrtnzlml** [benmosher/eslint-plugin-import#1250] opened 2018-12-20 18:52 UTC
Hello! 👋 I noticed when using this rule that when the `package.json` doesn't have `dependencies` (or dev deps) then this rule doesn't work and it seems like we have all the dependencies installed correctly. The same applies to the case where dependencies are just `{}`.

How to reproduce: open any project where it works and remove one dependency => you see it works correctly. Now, replace all the dependencies in `package.json` for just `"dependencies": {}` and run it again => you see no lint errors.

I believe expected behavior would be to throw many many errors in this case.

**Comment by ljharb** [comment] 2018-12-20 19:11
Duplicate of #1161; fixed in https://github.com/benmosher/eslint-plugin-import/commit/b0b6125844e28e2b63752b590c50cd8fad262c74 but not yet released.

**Closed by ljharb** 2018-12-20 19:11 UTC

**Comment by mrtnzlml** [comment] 2018-12-20 19:13
Ah, thanks! I couldn't find that issue... 🤦‍♂️ 😊

**Comment by mrtnzlml** [comment] 2018-12-27 13:33
@ljharb Do you know when are you going to release this bugfix, please? :)
