### ISSUE TITLE
import/order working inconsistenly on multiple platforms

### ISSUE THREAD

**Issue by RadarCZ** [benmosher/eslint-plugin-import#1710] opened 2020-03-30 15:49 UTC
I have a project, wiriting it on Windows 10 machine in vscode, then deploying it to Debian 10 VPS. ESLint is dev-dependency, same as `typescript`, `tslint`, `eslint-plugin-import`. ESLint configuration is same for both machines, as well as the run script for ESLint.

When I run ESLint on Windows, fix it, then deploy the project to VPS and run ESLint there, it reports errors from import/order. Other way around, when I fix it on server with `--fix` option then download the code back to Windows, Windows version reports the errors, which should be fixed from VPS.

**Comment by ljharb** [comment] 2020-03-31 00:03
Can you confirm your git autocrlf settings?

Can you provide examples of what exactly is being ordered? In other words, i'm wondering if there's filesystem differences - case sensitivity, for example.

**Comment by waterfoul** [comment] 2020-03-31 13:57
This is a duplicate of #1692 which is fixed

**Closed** 2020-03-31 14:40 UTC
Labels: import/export ordering
