### ISSUE TITLE
`import/no-unresolved` not works with `package.json`/`imports`

### ISSUE THREAD

**Issue by Eomm** [benmosher/eslint-plugin-import#2410] opened 2022-03-22 13:06 UTC
Hi,
given this `.eslintrc`:

```
{
  "extends": [
    "standard",
    "prettier",
    "eslint:recommended",
    "plugin:prettier/recommended"
  ],
  "env": {
    "node": true
  },
  "rules": {
    "import/no-unresolved": ["error", { "commonjs": true, "amd": true }]
  }
}
```

If I configure the `import` into the `package.json`:

```
  "imports": {
    "#libs/*": "./src/libs/*.js",
    "#services/*": "./src/services/*.js"
  },
```

I want to use it like this into the code:

```js
const getQueueKey = require('#libs/buildKey')
console.log(getQueueKey)
```

But I get the error:

```
Unable to resolve path to module '#libs/buildKey'.
```

<img width="591" alt="image" src="https://user-images.githubusercontent.com/11404065/159488229-9da6001d-1ad7-46bf-82e5-4de40fe508e9.png">

Running the code works as expected. The `console.log` prints out:

```
[Function: getQueueKey]
```

Do you have any idea how to solve it?

**Comment by ljharb** [comment] 2022-03-22 17:41
We indeed do not yet support `imports` resolution (or `exports`), because `resolve` does not yet support it.

Closing as a duplicate of #1810 and many others.

**Closed as completed by ljharb** 2022-03-22 17:41 UTC
