### ISSUE TITLE
add option to sort import in an alphabetical order

### ISSUE THREAD

**Issue by ozsay** [benmosher/eslint-plugin-import#1059] opened 2018-04-02 08:31 UTC
we use the `order` rule to group similar imports, which is very useful.

We would love to be able to sort alphabetically inside the groups (sort by the import path):

```
import fs from 'fs';
import path from 'path';
import crypto from 'crypto'; // fails because it should be before the fs import

import request from 'request';
import _ from 'lodash'; // fails because it should be before the request import
```

Thanks!

**Comment by billyjanitsch** [comment] 2018-04-06 18:54
Duplicate of #389.

**Closed** 2018-04-09 22:04 UTC
Labels: import/export ordering
