### ISSUE TITLE
import/order fails after updating a dependency (redux-saga)

### ISSUE THREAD

**Issue by mastilver** [benmosher/eslint-plugin-import#793] opened 2017-04-06 08:32 UTC
When using `redux-saga@0.14.4` everything is fine
But fails when using `redux-saga@0.14.5`

I think the reason for this to fails is this PR: https://github.com/redux-saga/redux-saga/pull/895

-----

Error message:

`./userSaga import should occur before import of redux-saga/effects             import/order`

Code: 

```js
import { fork } from 'redux-saga/effects';

import connectionFlow from './userSaga';
```

**Comment by vadimdemedes** [comment] 2017-04-06 09:19
I can confirm this issue is happening to me as well. `redux-saga` removed the `redux-saga/effects.js` file, so it freaks out `eslint-plugin-import`.

**Comment by Ephys** [comment] 2017-04-06 12:44
It's probably due to the fact that `redux-saga/effects.js` was replaced with a package.json file with a relative path as a main field ?

**Comment by jch254** [comment] 2017-04-20 02:17
Any update on this one? Cheers

**Comment by lourd** [comment] 2017-05-09 23:33
Also facing this issue. To add, it's peculiar that the linter reports this as a warning from the `import/order` plugin, but my editor integration reports it (more appropriately?) as `"Unable to resolve path to module 'redux-saga/effects'. (import/no-unresolved)`. This appears to compound the original issue because it's not possible to workaround the warning while the fix is resolved by simply disabling eslint on the line of the `redux-saga/effects` import

```js
// Doesn't help
import { put, call, takeEvery } from 'redux-saga/effects'; // eslint-disable-line
```

It still causes warnings for other imports in the file, namely `import/order`.

**Comment by artsafin** [comment] 2017-07-10 12:15
As a temporary workaround, one can add `redux-saga/effects` to `import/core-modules`.
That will make it at least higher that internal modules in the imports list.

Example:
```
    settings: {
        'import/core-modules': [
            'redux-saga/effects',
        ]
    },
```

**Comment by jonathanj** [comment] 2019-02-19 10:59
I'm still having this issue on 2.16.0:

```
1:25  error  Relative imports from parent directories are not allowed. Please either pass what you're importing through at runtime (dependency injection), move `session.js` to same directory as `redux-persist/constants` or consider making `redux-persist/constants` a package  import/no-relative-parent-imports```

```
11:8  error  Relative imports from parent directories are not allowed. Please either pass what you're importing through at runtime (dependency injection), move `index.js` to same directory as `redux-saga/effects` or consider making `redux-saga/effects` a package  import/no-relative-parent-imports```

**Closed** 2019-03-03 07:30 UTC
Labels: import/export ordering
