### ISSUE TITLE
warning "eslint-plugin-import@2.3.0" has incorrect peer dependency "eslint@2.x - 3.x"

### ISSUE THREAD

**Issue by i-break-codes** [benmosher/eslint-plugin-import#875] opened 2017-06-16 08:45 UTC
Any plans to upgrade the `eslint` package? Am currently on 4.0.0.

Edit: Added markdown to eslint

**Comment by ljharb** [comment] 2017-06-16 15:42
Duplicate of #870.

**Closed by ljharb** 2017-06-16 15:42 UTC
