### ISSUE TITLE
Importing node packages gives "missing extension" error

### ISSUE THREAD

**Issue by rayax86** [benmosher/eslint-plugin-import#650] opened 2016-11-03 07:39 UTC
`import pak from "pak"`

Maybe not a bug, but generally how do you solve this without turning the extensions rule off?

**Comment by benmosher** [comment] 2016-11-03 13:16
closing as dupe of #414, let me know if I am misunderstanding

**Closed by benmosher** 2016-11-03 13:16 UTC

**Comment by rayax86** [comment] 2016-11-03 13:29
Nope, the issue arises if an npm package named "pak" is imported as `import pak from "pak"`, with its entry point called "pak.js". It is different from having "pak/index.js" as its entry point.
