### ISSUE TITLE
no-named-as-default is extremely slow

### ISSUE THREAD

**Issue by leethree** [benmosher/eslint-plugin-import#1367] opened 2019-05-28 15:02 UTC
I'm running ESLint in a React Native project with Node v10.15.0. The `import` rules are very slow compared to others.

```
Rule                              | Time (ms) | Relative
:---------------------------------|----------:|--------:
import/no-named-as-default-member | 14161.088 |    55.4%
import/named                      |  6038.526 |    23.6%
import/no-unresolved              |  1203.911 |     4.7%
react/no-render-return-value      |   416.194 |     1.6%
react/prefer-stateless-function   |   354.205 |     1.4%
react/jsx-no-bind                 |   209.374 |     0.8%
react/no-deprecated               |   209.076 |     0.8%
import/no-extraneous-dependencies |   196.390 |     0.8%
import/no-useless-path-segments   |   190.158 |     0.7%
import/extensions                 |   134.902 |     0.5%
✨  Done in 72.53s.
```

Possibly related #1182

**Comment by ljharb** [comment] 2019-05-28 17:11
It’s not necessarily that rule, it’s that whichever rule runs first is “slow” because it had to build up the export map in your project, and the others have to wait on that happening.

On large projects, it’s relatively unavoidable (when linting across files) to pay some time for the import plugin to build up a dependency map.

**Comment by benmosher** [comment] 2019-06-29 01:44
`import` plugin has to parse _every_ dependency, whereas "normal" ESLint rules only need to inspect a small portion of the current file (that has already been parsed). The `import` parse time is recorded as part of the rule execution.

Using something like `eslint_d` to keep cached parses in memory could speed up your (re-)execution substantially. I have also considered implementing a filesystem version of the dependency map. 

Closing for now because this is well understood. Can reopen if you can provide evidence that a performance regression has occurred. Thanks!

**Closed by benmosher** 2019-06-29 01:44 UTC

**Comment by ljharb** [comment] 2019-06-29 01:51
It might also be possible to use haste-map, which isn’t what jest uses internally.
