### ISSUE TITLE
Add Eslint 6 in peerDependencies

### ISSUE THREAD

**Issue by jimblue** [benmosher/eslint-plugin-import#1391] opened 2019-06-22 15:27 UTC
Hi,

ESlint 6 have been release, could you please add it to the peerDependencies, thank you.

https://github.com/benmosher/eslint-plugin-import/blob/fc65509216dca4bb5a6a6d41c23348ba8cbb62c2/package.json#L80

**Comment by ljharb** [comment] 2019-06-22 15:36
Duplicate of #1362.

**Closed by ljharb** 2019-06-22 15:36 UTC
Labels: help wanted
