### ISSUE TITLE
v2.23 causes `no-extraneous-dependencies` errors for related `@types/` packages that aren't imported

### ISSUE THREAD

**Issue by neefrehman** [benmosher/eslint-plugin-import#2078] opened 2021-05-15 11:29 UTC
Since upgrading to v2.23 I'm seeing lot's of errors in my TypeScript codebase related to `@types` dependencies, even though they are not directly being imported. for example:

```ts
import React from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
```

Is throwing:

```shell
  3:1  error  '@types/react' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  4:1  error  '@types/three' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  5:1  error  '@types/three' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```

**Comment by marjorg** [comment] 2021-05-15 13:36
Can confirm this. Reverting to 2.22.1 for now

**Comment by buu700** [comment] 2021-05-15 14:33
Possibly related issue: I'm now getting `error  'rxjs/operators' should be listed in the project's dependencies. Run 'npm i -S rxjs/operators' to add it  import/no-extraneous-dependencies`, with `rxjs/operators` being a path within the `rxjs` package.

**Comment by ljharb** [comment] 2021-05-15 15:50
I believe this may be a duplicate of #2065, and possibly related to #2058.

**Comment by JuanpaG94** [comment] 2021-05-18 13:04
Can confirm this. Not only for `@types/` dependencies but everything that has other packages inside the dependency.
For example `styled-components/native` or similar.

**Comment by cloudagon** [comment] 2021-05-21 16:25
Thanks for reporting this. I thought I was going crazy.

**Comment by henryjin3** [comment] 2021-05-27 12:00
Is this addressed by #2097?

**Closed** 2021-05-27 17:35 UTC

**Comment by VirajKanse** [comment] 2021-06-20 09:54
is this fixed yet or not?
Am still facing same issue for @chakra-ui/layout & other components

**Comment by ljharb** [comment] 2021-06-20 14:43
Yes, it’s fixed in v2.23.4. If you’re still seeing it, please file a new issue.
