### ISSUE TITLE
Problem with using import/extensions in project

### ISSUE THREAD

**Issue by jarlah** [benmosher/eslint-plugin-import#705] opened 2016-12-30 14:29 UTC
Hi

I am trying to use import/extensions as follows:

```"import/extensions": [2, { "js": "always", "jsx": "always" }],```

This results in the following error:

```Missing file extension "js" for "react"              import/extensions```

Why? Is there any way to ignore non-relative paths? 

I want to require extensions for all import statements, except for the import statements that are not relative.

**Comment by k15a** [comment] 2017-01-01 14:19
Duplicate of #414

**Comment by mrbone** [comment] 2017-04-14 15:22
you can set in `settings`

```
"import/ignore": [
      "node_modules",
      "\\.json$"
    ],
```

**Closed** 2017-04-14 15:32 UTC
