### ISSUE TITLE
New rule idea: "no-unused-modules"

### ISSUE THREAD

**Issue by torarnek** [benmosher/eslint-plugin-import#361] opened 2016-05-31 10:39 UTC
Problem: In larger projects unused modules tend to lay around, and it is tiresome to find these modules (for deletion). It would be nice enforce/warn about unused modules.

As the resolving needs a starting point we can provide a regexp. In my current project we have two ways to express entries, either simply being a file in /pages/, or having Init.js extension, e.g. ProfileInit.js

```
import/no-unused-modules: [2, { entry: /Init\.js$|\/pages\// }]
```
Any files that not imported recursively can listet. 

I would love this feature! :)

**Comment by benmosher** [comment] 2016-05-31 10:45
closing as dupe of #186. I agree, would be super-cool 😎

**Closed by benmosher** 2016-05-31 10:45 UTC
