### ISSUE TITLE
Enforce imports paths from project's root

### ISSUE THREAD

**Issue by antarestupin** [benmosher/eslint-plugin-import#1420] opened 2019-07-17 11:58 UTC
Hi,

In my team we have a convention to always use imports with paths starting from the project's root instead of relative paths. For example:

- `import { x } from 'src/path/to/module';` is correct
- `import { x } from '../to/module';` is wrong
- `import { x } from './module';` is wrong

I found no rule to enforce this convention, but I think this need may be quite common.

Would you be interested in having such a rule? If so I can propose a PR to add this feature.

Thanks!

**Comment by ljharb** [comment] 2019-07-17 16:33
Why would this be common? It seems like this would massively increase the diff churn whenever a directory of files is moved, for example.

**Comment by antarestupin** [comment] 2019-07-18 15:52
Good point. What would you recommend as a convention? Using relative paths instead of these ones? I'd like to let the choice, with configuration or by using 2 rules for example.

**Comment by ljharb** [comment] 2019-07-19 05:58
I'd expect relative paths always; with a potential rule that prevents use of `..`, either anywhere, or at specific levels in the hierarchy. Personally I prefer never to create confusing aliases, and to just use the `../` as needed.

**Comment by antarestupin** [comment] 2019-07-22 15:28
It sounds interesting, I've seen that there is even already the [no-relative-parent-imports](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-relative-parent-imports.md) rule that can help for that.

As other developers may prefer using another conventions (or just cannot change them), would you prefer letting the users of this plugin having the choice with several rules or encourage one convention by having only one possibility?

**Comment by ljharb** [comment] 2019-07-22 15:30
There’s a balance between allowing configuration and allowing rules that don’t encourage good practice; imo i think this should be a custom rule if you aren’t persuaded it’s a bad practice.

**Comment by antarestupin** [comment] 2019-07-23 12:48
I was thinking the same thing. Still, a rule to enforce the use of relative path could be useful. Would you be interested in adding it in this plugin? If so I can try working on it.

**Comment by ljharb** [comment] 2019-07-23 17:41
That seems more related to #1154, or a duplicate of #669; but also see https://github.com/benmosher/eslint-plugin-import/issues/669#issuecomment-316438608

**Comment by antarestupin** [comment] 2019-07-31 12:30
My idea was dumber than those in the issues you linked, it's just about checking the path is relative; for example checking that either:

- it starts with a `./` or `../`
- the first part of it is a file or folder in the same folder as the file making the import

And just this, nothing cleverer.

**Comment by ljharb** [comment] 2019-08-01 05:30
Wouldn't that preclude bare imports?

**Comment by antarestupin** [comment] 2019-08-05 09:36
Indeed it would... I guess I can check if the path is in `node_modules`, but it may become too much work to process for each path for a rule. What do you think about this? Do you see another solution?

**Comment by ljharb** [comment] 2019-08-05 23:09
I guess I’m not clear on the purpose. Why is it better to start from the project root, forcing the maximum amount of git churn when a file is moved or renamed? It sounds like the opposite of what you’d want (the rule for which already exists)

**Comment by antarestupin** [comment] 2019-08-07 15:33
At the beginning I wanted to add a rule to do this (always start from the project root), but as we discussed I realized the opposite is better. Now I want to make a rule to avoid it instead. Which rule can do that?

**Comment by ljharb** [comment] 2019-08-08 01:49
You'd have to do extra config to make the `src` thing work - so I'm not sure if you need a rule, when you can just remove the config that allows it, and it will be the default behavior which is "only relative paths can possibly work"? (assuming you also have https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-absolute-path.md enabled)

**Comment by antarestupin** [comment] 2019-08-09 14:43
You're right! Then indeed no new rule is needed. Thank you for your help and explanations, I'll close this issue.

**Closed** 2019-08-09 14:43 UTC
