### ISSUE TITLE
Exclude binary files by default from `no-unused-modules`.

### ISSUE THREAD

**Issue by ehmicky** [benmosher/eslint-plugin-import#1328] opened 2019-04-14 13:27 UTC
`missingExports: true` of the `no-unused-modules` rule should not report files that are in the `bin` field of `package.json`. Binary entry files are usually not meant to export variables but instead to communicate to the shell using stdout/stderr and exit codes.

What do you think? Thanks.

**Comment by ljharb** [comment] 2019-04-14 15:39
This seems like a duplicate of #1327?

**Closed** 2019-04-14 15:39 UTC

**Comment by ehmicky** [comment] 2019-04-14 16:51
#1327 was about `unusedExports`. This one is about `missingExports`. As opposed to `unusedExports`, this might only make sense for `bin` files.

**Comment by ljharb** [comment] 2019-04-14 18:40
ahh gotcha. I’d expect all those to be ignored for both tho, since entry points need not export anything, even main, and especially browser.

**Comment by ehmicky** [comment] 2019-04-14 18:56
> since entry points need not export anything, even main

As opposed to `bin` files, shouldn't most `main` files export something? Otherwise requiring them would not return a value.

**Comment by ljharb** [comment] 2019-04-14 22:55
They need not. Packages can be required solely for side effects - minority is irrelevant; what matters is that it’s nonzero and appropriate.

If a file is explicitly declared as an entry point - whether in the rule config, main, bin, or browser - then I’m convinced it’s useless to be checking for used exports.

**Comment by ehmicky** [comment] 2019-04-14 22:59
This makes sense. Also this allows merging those two issues.
