### ISSUE TITLE
specify something like `ignoreImports` for no-unused-modules rule

### ISSUE THREAD

**Issue by schumannd** [benmosher/eslint-plugin-import#1488] opened 2019-09-25 12:12 UTC
I think it might be useful to implement a `ignoreImports` or `ignoreFiles` option for the `no-unused-modules` rule.

This would help in the scenario, where I want to ignore certain files (e.g. tests) that might reference otherwise unreferenced code.

**Comment by ljharb** [comment] 2019-09-25 14:52
Duplicate of #1452.

**Closed by ljharb** 2019-09-25 14:52 UTC
