### ISSUE TITLE
unused-modules ignore tests

### ISSUE THREAD

**Issue by benmonro** [benmosher/eslint-plugin-import#1465] opened 2019-08-29 19:46 UTC
when using the unused-modules rule, is it possible to have the rule ignore tests?  in other words, if the file is only used by tests, I STILL want it to report an error if it's not imported anywhere else.  Do i just need to turn off the lint rule in the `__tests__` folder?

note our `__tests__` folder follows the default jest pattern where the tests are next to the src

**Comment by ljharb** [comment] 2019-08-30 07:37
Duplicate of your own #1452.

**Closed by ljharb** 2019-08-30 07:37 UTC

**Comment by benmonro** [comment] 2019-08-30 13:07
Doh!  My bad been one of those weeks
