### ISSUE TITLE
Pattern matching errors for dynamic-import-chunkname

### ISSUE THREAD

**Issue by KnightYoshi** [benmosher/eslint-plugin-import#1298] opened 2019-03-06 02:02 UTC
Webpack has various output templates that do not match chunkname regex

<img width="913" alt="screen shot 2019-03-05 at 20 45 57" src="https://user-images.githubusercontent.com/6134576/53850586-c3d38700-3f89-11e9-8ff5-ed9d641ede50.png">

**Comment by ljharb** [comment] 2019-03-06 06:44
Duplicate of #1181. See also #1163, #1130.

**Closed by ljharb** 2019-03-06 06:44 UTC
