### ISSUE TITLE
[order] Separate handling of regular imports and type imports

### ISSUE THREAD

**Issue by vmk1vmk** [benmosher/eslint-plugin-import#2016] opened 2021-03-26 13:21 UTC
I would like to split the imports into **regular** imports and **type** imports and apply the specified ordering on each of them individually.

Example: 
```ts
/**
 *  Regular imports
 */
import fs from 'fs';
import _ from 'lodash';
// etc.

/**
 *  Type imports
 */
import type { File } from 'fs';
import type { LoDashStatic } from 'lodash';
// etc.
```

How could I achieve that behaviour with the order rule?

Thank you for helping in advance.

**Comment by ljharb** [comment] 2021-03-26 15:05
I think we'd need to add a "group" to the rule for type imports for this to be possible.

**Comment by vmk1vmk** [comment] 2021-03-27 11:30
I would consider `group` and `importTypeGroups` to be different dimensions.

Maybe there should be two stages in the rule:
1. Group and sort by import type
2. Group and sort inside import type with the specified `group` ordering

The proposed Option could be called `importTypeGroup` and look like the following code.
```ts
type ImportTypeGroup = Default | TypeFirst | RegularFirst;

type Default = [
  ['regular', 'type'] // (default) treat them as the same
];

type TypeFirst = [
  'type',
  'regular'
];

type RegularFirst = [
 'regular',
  'type'
];
```
The Option behaves almost identical as `group`.
Also the default preserves the current behaviour and would therefore not bother pure JS users.

Options that are modifying the behaviour of `group` could be also considered here, like `newlines-between`.

This is currently my best guess on how to implement an easy and clear API that doesn't have to concern non TS users.

**Comment by bobaaaaa** [comment] 2021-03-31 12:32
There is also the issue #645 with some comments in it.

**Comment by ljharb** [comment] 2021-03-31 14:59
In that case, let’s close this as a duplicate of #645 and consolidate discussion there.

**Closed by ljharb** 2021-03-31 14:59 UTC
Labels: import/export ordering, typescript
