### ISSUE TITLE
import/no-extraneous-dependencies needs exclude option for specific module

### ISSUE THREAD

**Issue by Fnxxxxo** [benmosher/eslint-plugin-import#1817] opened 2020-06-11 03:32 UTC
I'm use Nuxt to manage my project. Nuxt manage all vue-related dependencies in its own version which allow us to us `import Vue from 'vue` without additional config. When using import/no-extraneous-dependencies, it raise errors. Any way to exclude them?

**Comment by ljharb** [comment] 2020-06-11 05:47
Are you saying that Nuxt implicitly adds `import Vue from 'vue'` into all your code? or are you saying that you don't have to add vue to your package.json because nuxt ensures it's available?

**Comment by Fnxxxxo** [comment] 2020-06-16 06:40
@ljharb Nuxt manage versions of vue and vuex for us. And they dont recommend to add vue manually.

**Comment by ljharb** [comment] 2020-06-16 06:50
That seems like a really terrible idea that prevents an entire ecosystem of static analysis tools.

Either way, duplicate of #903.

**Closed by ljharb** 2020-06-16 06:50 UTC
