### ISSUE TITLE
eslint 7 support

### ISSUE THREAD

**Issue by gabegorelick** [benmosher/eslint-plugin-import#1756] opened 2020-05-11 20:55 UTC
eslint 7.0.0 was just released and eslint-plugin-import should support it. Currently, it's out of range of the `peerDependency` so you get an error on install.

See https://eslint.org/docs/user-guide/migrating-to-7.0.0

**Comment by ljharb** [comment] 2020-05-11 21:00
Duplicate of #1752; done in 6a110dd16a7fd775f08601054bf14ffd503eea7b, just not yet released. It will be in the next release.

**Closed by ljharb** 2020-05-11 21:00 UTC
