### ISSUE TITLE
False positive for date-fns

### ISSUE THREAD

**Issue by ilyub** [benmosher/eslint-plugin-import#2113] opened 2021-06-03 06:24 UTC
```ts
import enGB from "date-fns/locale/en-GB";
import enUS from "date-fns/locale/en-US";
```

I get this warning:
'...\node_modules\date-fns\typings.d.ts' imported multiple times. eslint (import/no-duplicates)

**Comment by ljharb** [comment] 2021-06-03 06:50
This is a duplicate of #2068.

**Closed by ljharb** 2021-06-03 06:50 UTC
