### ISSUE TITLE
import/order incorrectly classifies nested node_modules packages

### ISSUE THREAD

**Issue by ntucker** [benmosher/eslint-plugin-import#899] opened 2017-07-20 22:29 UTC
### Repro:
1. Install redux-saga
2. import 'redux-saga/effects'
3. See linter think it should be the in group with 'internal'

**Comment by SpainTrain** [comment] 2017-08-02 06:30
dupe of https://github.com/benmosher/eslint-plugin-import/issues/793 ?

**Comment by ljharb** [comment] 2017-08-02 06:40
Duplicate of #793, indeed

**Closed by ljharb** 2017-08-02 06:40 UTC
