### ISSUE TITLE
`import/extensions` doesn't work with inline Webpack loader syntax

### ISSUE THREAD

**Issue by TimonVS** [benmosher/eslint-plugin-import#2162] opened 2021-07-22 09:55 UTC
When updating from 2.22.1 to 2.23.4 errors started showing up for these kind of imports:

```
// ESLint error: Missing file extension for "!!raw-loader!./SimpleSceneLayerExample" eslint import/extensions
const exampleText: string = require('!!raw-loader!./SimpleSceneLayerExample').default;
// Same error
import exampleText from '!!raw-loader!./SimpleSceneLayerExample';
```

If I do add the extension, I'll get an error that I shouldn't use the extension:

```
// ESLint error: Unexpected use of file extension "tsx" for "!!raw-loader!./SimpleSceneLayerExample.tsx" eslint import/extensions
const exampleText: string = require('!!raw-loader!./SimpleSceneLayerExample.tsx').default;
```

This is our ESLint config (I removed all rules except for import/extensions to test if no other rules are conflicting):

```
{
    "plugins": ["@typescript-eslint"],
    "parser": "@typescript-eslint/parser",
    "settings": {
        "import/resolver": {
            "node": {
                "extensions": [".mjs", ".js", ".json", ".ts", ".tsx"]
            }
        },
        "import/extensions": [".js", ".mjs", ".jsx", ".ts", ".tsx"]
    },
    "rules": {
        "import/extensions": [
            "error",
            "ignorePackages",
            {
                "js": "never",
                "mjs": "never",
                "jsx": "never",
                "ts": "never",
                "tsx": "never"
            }
        ]
    },
    "env": {
        "jest": true,
        "browser": true
    }
}
```

I noticed that on 2.22.1 require statements weren't checked for import extensions, so I think the problem is that `import/extensions` can't handle inline Webpack loader syntax properly.

```ts
// This is fine in  2.22.1 with the above rules
const exampleText: string = require('!!raw-loader!./SimpleSceneLayerExample.tsx').default;
// This results in an error in both 2.22.1 and 2.23.4
// ESLint error: Unexpected use of file extension "tsx" for "./SimpleSceneLayerExample.tsx" eslint import/extensions
import { SimpleSceneLayerExample } from './SimpleSceneLayerExample.tsx';
```

**Comment by ljharb** [comment] 2021-07-22 17:33
That's because this is nonstandard syntax (that shouldn't be used anyways), and as such, your specifier doesn't *have* an extension.

File paths have extensions, and this isn't a file path.

Either way, this is a duplicate of #954.

**Closed by ljharb** 2021-07-22 17:33 UTC
