### ISSUE TITLE
import/no-unresolved can't resolve module under node_modules/@types

### ISSUE THREAD

**Issue by tjx666** [benmosher/eslint-plugin-import#1695] opened 2020-03-24 02:11 UTC
![screenshot_2020-03-24_10-09-21](https://user-images.githubusercontent.com/41773861/77380985-a43b1680-6db7-11ea-98c6-4ba849d34cf0.png)

versions: 
```
"eslint": "^6.8.0",
"eslint-import-resolver-typescript": "^2.0.0",
"eslint-plugin-import": "2.20.1",
"typescript": "^3.8.3",
"@typescript-eslint/eslint-plugin": "^2.25.0",
"@typescript-eslint/parser": "^2.25.0",
```

**Comment by ljharb** [comment] 2020-03-24 02:28
Your image points to `@types/html-minifier`, not `html-minifier`.

**Comment by tjx666** [comment] 2020-03-24 02:35
@ljharb not existed，but I didn't have this problem before. If I using `@types/html-minifier`, tsc will throw another error:

![screenshot_2020-03-24_10-34-32](https://user-images.githubusercontent.com/41773861/77382334-1b25de80-6dbb-11ea-8759-d02de5c0135f.png)

**Comment by ljharb** [comment] 2020-03-24 03:39
ah, i think this is a duplicate of #1618?

**Closed by ljharb** 2020-03-24 03:39 UTC
